# Generated by Django 5.2 on 2025-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_menu_items',
            field=models.BooleanField(default=False, help_text='Whether the reservation includes pre-ordered menu items'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prepare_ahead',
            field=models.BooleanField(default=False, help_text='Whether to prepare food 20 minutes before reservation time'),
        ),
    ]
