# Generated by Django 5.2 on 2025-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='has_placed_order',
            field=models.BooleanField(default=False, help_text='Whether the customer has placed an order for this reservation'),
        ),
    ]
